// Generated by gencpp from file edge_detection_service/EdgePoint.msg
// DO NOT EDIT!


#ifndef EDGE_DETECTION_SERVICE_MESSAGE_EDGEPOINT_H
#define EDGE_DETECTION_SERVICE_MESSAGE_EDGEPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edge_detection_service
{
template <class ContainerAllocator>
struct EdgePoint_
{
  typedef EdgePoint_<ContainerAllocator> Type;

  EdgePoint_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  EdgePoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::edge_detection_service::EdgePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edge_detection_service::EdgePoint_<ContainerAllocator> const> ConstPtr;

}; // struct EdgePoint_

typedef ::edge_detection_service::EdgePoint_<std::allocator<void> > EdgePoint;

typedef boost::shared_ptr< ::edge_detection_service::EdgePoint > EdgePointPtr;
typedef boost::shared_ptr< ::edge_detection_service::EdgePoint const> EdgePointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edge_detection_service::EdgePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edge_detection_service::EdgePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edge_detection_service::EdgePoint_<ContainerAllocator1> & lhs, const ::edge_detection_service::EdgePoint_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edge_detection_service::EdgePoint_<ContainerAllocator1> & lhs, const ::edge_detection_service::EdgePoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edge_detection_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edge_detection_service::EdgePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edge_detection_service::EdgePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edge_detection_service::EdgePoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::edge_detection_service::EdgePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edge_detection_service/EdgePoint";
  }

  static const char* value(const ::edge_detection_service::EdgePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::edge_detection_service::EdgePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EdgePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edge_detection_service::EdgePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edge_detection_service::EdgePoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDGE_DETECTION_SERVICE_MESSAGE_EDGEPOINT_H
