// Generated by gencpp from file edge_detection_service/EdgeDetection.msg
// DO NOT EDIT!


#ifndef EDGE_DETECTION_SERVICE_MESSAGE_EDGEDETECTION_H
#define EDGE_DETECTION_SERVICE_MESSAGE_EDGEDETECTION_H

#include <ros/service_traits.h>


#include <edge_detection_service/EdgeDetectionRequest.h>
#include <edge_detection_service/EdgeDetectionResponse.h>


namespace edge_detection_service
{

struct EdgeDetection
{

typedef EdgeDetectionRequest Request;
typedef EdgeDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EdgeDetection
} // namespace edge_detection_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edge_detection_service::EdgeDetection > {
  static const char* value()
  {
    return "544ac8dfe4746ee920a8bc72050eac6c";
  }

  static const char* value(const ::edge_detection_service::EdgeDetection&) { return value(); }
};

template<>
struct DataType< ::edge_detection_service::EdgeDetection > {
  static const char* value()
  {
    return "edge_detection_service/EdgeDetection";
  }

  static const char* value(const ::edge_detection_service::EdgeDetection&) { return value(); }
};


// service_traits::MD5Sum< ::edge_detection_service::EdgeDetectionRequest> should match
// service_traits::MD5Sum< ::edge_detection_service::EdgeDetection >
template<>
struct MD5Sum< ::edge_detection_service::EdgeDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edge_detection_service::EdgeDetection >::value();
  }
  static const char* value(const ::edge_detection_service::EdgeDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edge_detection_service::EdgeDetectionRequest> should match
// service_traits::DataType< ::edge_detection_service::EdgeDetection >
template<>
struct DataType< ::edge_detection_service::EdgeDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::edge_detection_service::EdgeDetection >::value();
  }
  static const char* value(const ::edge_detection_service::EdgeDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edge_detection_service::EdgeDetectionResponse> should match
// service_traits::MD5Sum< ::edge_detection_service::EdgeDetection >
template<>
struct MD5Sum< ::edge_detection_service::EdgeDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edge_detection_service::EdgeDetection >::value();
  }
  static const char* value(const ::edge_detection_service::EdgeDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edge_detection_service::EdgeDetectionResponse> should match
// service_traits::DataType< ::edge_detection_service::EdgeDetection >
template<>
struct DataType< ::edge_detection_service::EdgeDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::edge_detection_service::EdgeDetection >::value();
  }
  static const char* value(const ::edge_detection_service::EdgeDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDGE_DETECTION_SERVICE_MESSAGE_EDGEDETECTION_H
